export const Userdata = [
  {
    hobbies: ["Reading", "Hiking", "Photography"],
    interests: ["Technology", "Art", "Traveling"],
    gender: "Male",
    img: "https://static.vecteezy.com/system/resources/thumbnails/047/462/770/small_2x/positive-man-on-clean-background-photo.jpg",
    distance: "1.3",
    firstName: "Franky",
    lastName: "Wilson",
    age: "20",
    place: "HANOVE",
    isOnline: true,
    match: "83",
  },
  {
    hobbies: ["Cooking", "Gaming", "Cycling"],
    interests: ["Science", "History", "Music"],
    gender: "Female",
    img: "https://www.heysaturday.co/wp-content/uploads/2016/11/best-dating-profile-photos-women-b.jpg",
    distance: "2",
    firstName: "Catherine",
    lastName: "John",
    age: "23",
    place: "New York",
    isOnline: true,
    match: "94",
  },
  {
    hobbies: ["Drawing", "Yoga", "Gardening"],
    interests: ["Fashion", "Health", "Design"],
    gender: "Male",
    img: "https://media.istockphoto.com/id/1476170969/photo/portrait-of-young-man-ready-for-job-business-concept.jpg?b=1&s=170667a&w=0&k=20&c=FycdXoKn5StpYCKJ7PdkyJo9G5wfNgmSLBWk3dI35Zw=",
    distance: "1.3",
    firstName: "David",
    lastName: "Johnson",
    age: "20",
    place: "CHICAGO",
    isOnline: true,
    match: "87",
  },
  {
    hobbies: ["Fishing", "Golf", "Reading"],
    interests: ["Politics", "Economics", "Photography"],
    img: "https://media.istockphoto.com/id/1682296067/photo/happy-studio-portrait-or-professional-man-real-estate-agent-or-asian-businessman-smile-for.webp?b=1&s=170667a&w=0&k=20&c=V-RXoAk73ljzQZd0w_JcCFG-jlYs6sjpcrIZQ1TersQ=",
    distance: "2",
    firstName: "Bob",
    lastName: "Smith",
    age: "23",
    place: "AUSTIN",
    isOnline: true,
    match: "100"
  },
  {
    hobbies: ["Running", "Knitting", "Cooking"],
    interests: ["Wellness", "Food", "Traveling"],
    gender: "Male",
    img: "https://s3-alpha-sig.figma.com/img/1398/2ffd/fdadcd413286d1957a6b477eab57205f?Expires=1724025600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=Fyv-UpKabPLzCwmnRfnS4Zkd8w6HhY054t~-uy4bp89gyGLodfdzGO0xJ9ugFyJ7tqdnnTII~I84qNrLl96suXrsHDy~ohOCkJy7DJbwkSSD6TqQP5XQdkCq~g2XJ65KF-4qLW9A2jAy2NpUaXtaRedv9ycC9I2Cz6t-RAhmysAgimS-twjvZVgEAAR7KjE8aiQvsRd832rtVc8-e89Og0Udr-QVrXtOSj-cP~tAHowQcj18vyJhQpzFfst4ct9xgxIhS5V0s3eAdwSjPTqtDRJlfOtBsdrVuc174Joe~s~YIE75rZ~tSTGEfQ~zm5ARlCd79p7wpP-gYKg2qEx-9g__",
    distance: "1.3",
    firstName: "James",
    lastName: "Wilson",
    age: "20",
    place: "HANOVE",
    isOnline: true,
    match: "50",
  },
  {
    hobbies: ["Surfing", "Gaming", "Music"],
    interests: ["Technology", "Sports", "Movies"],
    gender: "Male",
    img: "https://s3-alpha-sig.figma.com/img/9fba/bf04/a8e4d3ead51b45db5f3b4401dfa81421?Expires=1724025600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=U6iJ3dfbTmwH9TSbpKKjZExcz12wggW-khjbp2KkeFalhvVyTJtKmoLwVUukGEwgv9vvb1tXUp~QxpAvPeCPsrHLZLwotGxcNdcKjUzIbOqkQlHzq5JBWj5gEGX~xyHSK9tDDWverDXwK~JN75XpjY7FaxggY1nd1kP~gHrpvv2w2vPVwA0p96-oxvPN84LDozFwwRUivC0WEwJfaU-ejb0Yz7BoKy0yd4CdoRoymLl1OfMacbhnDol1g6EedFSVdxV~1-fjuDgdNK9r0hEgP5PmI8ldmNd1eHzMImmUNulVZR4Ukl0X0V7eB5fewkd5YB-36-tve2IFZVwXpO83qA__",
    distance: "2",
    firstName: "Eddie",
    lastName: "Johnson",
    age: "23",
    place: "DORTMUND",
    isOnline: true,
    match: "100",
  },
  {
    hobbies: ["Dancing", "Photography", "Traveling"],
    interests: ["Culture", "Fashion", "Art"],
    gender: "Female",
    img: "https://media.istockphoto.com/id/1437816897/photo/business-woman-manager-or-human-resources-portrait-for-career-success-company-we-are-hiring.jpg?s=612x612&w=0&k=20&c=tyLvtzutRh22j9GqSGI33Z4HpIwv9vL_MZw_xOE19NQ=",
    distance: "1.7",
    firstName: "Nami",
    lastName: "San",
    age: "20",
    isOnline: true,
    place: "MIAMI",
    match: "70",
  },
  {
    hobbies: ["Woodworking", "Hiking", "Cycling"],
    interests: ["Nature", "Science", "DIY Projects"],
    gender: "Male",
    place: "DENVER",
    img: "https://www.mensjournal.com/.image/t_share/MTk2MTM2NTcwNDMxMjg0NzQx/man-taking-selfie.jpg",
    distance: "1.5",
    firstName: "Brook",
    lastName: "Williams",
    age: "22",
    isOnline: true,
    match: "60"
  },
  {
    hobbies: ["Painting", "Yoga", "Reading"],
    interests: ["Wellness", "Design", "Art"],
    gender: "Female",
    img: "https://www.shutterstock.com/image-photo/headshot-portrait-smiling-african-american-600nw-1667439898.jpg",
    place: "PHOENIX",
    distance: "1.8",
    firstName: "Isabella",
    lastName: "Johnson",
    age: "21",
    isOnline: true,
    match: "90"
  },
  {
    hobbies: ["Running", "Traveling", "Gaming"],
    interests: ["Technology", "Fitness", "Movies"],
    gender: "Male",
    place: "BOSTON",
    img: "https://clubcorvettemontreal.com/news/img-m_p/profile-pictures-for-men_19_187990.jpg",
    distance: "1.2",
    firstName: "Jack",
    lastName: "Sparrow",
    age: "24",
    isOnline: true,
    match: "85"
  },
];

