export const users = [
    {
        id: 1,
        name: 'John Doe',
        img: "https://images.unsplash.com/photo-1496345875659-11f7dd282d1d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        about: "A software engineer with a passion for full-stack development.",
        interest: ["Coding", "Gaming", "Reading"],
        city: "New York",
        country: "USA",
        age: 28,
        active: true,
    },
    {
        id: 2,
        name: 'Jane Smith',
        img: "https://via.placeholder.com/150",
        about: "A digital marketer who loves creating engaging content.",
        interest: ["Marketing", "Photography", "Travel"],
        city: "Los Angeles",
        country: "USA",
        age: 32,
        active: true,
    },
    {
        id: 3,
        name: 'Carlos Hernandez',
        img: "https://via.placeholder.com/150",
        about: "An entrepreneur focused on building innovative tech startups.",
        interest: ["Startups", "Networking", "Investing"],
        city: "San Francisco",
        country: "USA",
        age: 35,
        active: false,
    },
    {
        id: 4,
        name: 'Emma Wilson',
        img: "https://via.placeholder.com/150",
        about: "A UX/UI designer who enjoys crafting user-friendly interfaces.",
        interest: ["Design", "Art", "Cycling"],
        city: "London",
        country: "UK",
        age: 29,
        active: true,
    },
    {
        id: 5,
        name: 'Li Wei',
        img: "https://via.placeholder.com/150",
        about: "A data scientist with a knack for finding patterns in data.",
        interest: ["Data Science", "AI", "Cooking"],
        city: "Beijing",
        country: "China",
        age: 30,
        active: false,
    }
];
