export const Userdata = [
    {
      name: "Alice Johnson",
      age: 28,
      hobbies: ["Reading", "Hiking", "Photography"],
      interests: ["Technology", "Art", "Traveling"],
      gender: "Female",
      place: "San Francisco, CA",
      status: "online",
    },
    {
      name: "Bob Smith",
      age: 35,
      hobbies: ["Cooking", "Gaming", "Cycling"],
      interests: ["Science", "History", "Music"],
      gender: "Male",
      place: "Austin, TX",
      status: "offline",
    },
    {
      name: "Catherine Lee",
      age: 24,
      hobbies: ["Drawing", "Yoga", "Gardening"],
      interests: ["Fashion", "Health", "Design"],
      gender: "Female",
      place: "New York, NY",
      status: "online",
    },
    {
      name: "David Brown",
      age: 42,
      hobbies: ["Fishing", "Golf", "Reading"],
      interests: ["Politics", "Economics", "Photography"],
      gender: "Male",
      place: "Chicago, IL",
      status: "offline",
    },
    {
      name: "Emily Davis",
      age: 31,
      hobbies: ["Running", "Knitting", "Cooking"],
      interests: ["Wellness", "Food", "Traveling"],
      gender: "Female",
      place: "Seattle, WA",
      status: "online",
    },
    {
      name: "Frank Wilson",
      age: 29,
      hobbies: ["Surfing", "Gaming", "Music"],
      interests: ["Technology", "Sports", "Movies"],
      gender: "Male",
      place: "Los Angeles, CA",
      status: "offline",
    },
    {
      name: "Grace Kim",
      age: 27,
      hobbies: ["Dancing", "Photography", "Traveling"],
      interests: ["Culture", "Fashion", "Art"],
      gender: "Female",
      place: "Miami, FL",
      status: "online",
    },
    {
      name: "Henry Miller",
      age: 33,
      hobbies: ["Woodworking", "Hiking", "Cycling"],
      interests: ["Nature", "Science", "DIY Projects"],
      gender: "Male",
      place: "Denver, CO",
      status: "offline",
    },
    {
      name: "Isabella Martinez",
      age: 26,
      hobbies: ["Painting", "Yoga", "Reading"],
      interests: ["Wellness", "Design", "Art"],
      gender: "Female",
      place: "Phoenix, AZ",
      status: "online",
    },
    {
      name: "Jack Taylor",
      age: 39,
      hobbies: ["Running", "Traveling", "Gaming"],
      interests: ["Technology", "Fitness", "Movies"],
      gender: "Male",
      place: "Boston, MA",
      status: "offline",
    },
  ];
  
